name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - run: ls -l # Liste les fichier du répertoire courant
      - uses: actions/checkout@v4
        with:
          path: '.github/workflows'
      - run: cat README.md # Affiche le contenu du fichier `README.md` à la base du dépôt